package factoryEnvironment;

public enum EnvironmentList {
	DEV_FRONTEND, TESTING_FRONTEND, PRODUCTION_FRONTEND, STAGING_FRONTEND,
	DEV_BACKEND, TESTING_BACKEND, PRODUTION_BACKEND, STAGING_BACKEND;
}
